let productsDb = [
    {      id : 1,
        title : "Sportswear",
        price : 150 ,           
        category : "Sport",
        imageUrl : "images/sport.jpg",
        qty : 1,
    },
    {      id : 2,
        title : "Pajamas",
        price : 120,           
        category : "Fashion",
        imageUrl : "images/sport.png",
        qty : 1,
    },
    {      id : 3,
        title : "Shoes-adidas",
        price : 120 ,           
        category : "sportshoes",
        imageUrl : "images/shoes.png",
        qty : 1,
    },
    {      id : 4,
        title : "Shoes-nike",
        price : 120,           
        category : "sportshoes",
        imageUrl : "images/shoes3.png",
        qty : 1,
    },
        {      id : 5,
        title : "Bag-red",
        price : 50 ,           
        category : "Fashion",
        imageUrl : "images/bag.png",
        qty : 1,
    },
    {      id : 6,
        title : "Bag-pink",
        price : 70,           
        category : "Fashion",
        imageUrl : "images/bag2.png",
        qty : 1,
    },
    {      id : 7,
        title : "Suitcase",
        price : 120 ,           
        category : "Bag",
        imageUrl : "images/bag1.png",
        qty : 1,
    },
    {      id : 8,
        title : "pajama-sport",
        price : 120,           
        category : "Sport",
        imageUrl : "images/aa.jpg",
        qty : 1,
    }
];
localStorage.setItem("products", JSON.stringify(productsDb));